TRAIN:
  EPOCHS: 50
  BATCH_SIZE: 512
  INIT_LR: 1e-2
  WEIGHT_DECAY: 0.001
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_START_EPOCH: 50
  LR_DECAY_METHOD: EXP
  DEVICE: cuda:0
  # DEVICE: cpu
  # MODE: clean
  MODE: cert

TEST:
  BATCH_SIZE: 256
  MODE: adv
  # MODE: clean
  IBP: True
  BERN_IBP: True
  # PGD: True
  PGD: False
  DEVICE: cuda:0
  # DEVICE: cpu

ROBUSTNESS:
  ENABLE: False
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 0.9
  MIN_BETA: 0.0
  MAX_BETA: 0.0
  WARMUP_EPOCHS: 0
  ROBUST_TRAINING_START_EPOCH: 0
  ROBUST_TRAINING_LAST_EPOCH: 100
  EPS_START_EPOCH: 1
  EPS_LAST_EPOCH: 1
  MAX_EPS: 0.1
  MIN_EPS: 0.1
  TEST_EPS: 0.1
  TEST_EVERY_N_EPOCH : 1

MODEL:
  TYPE: FC
  HIDDEN_LAYERS: [100,100,100]
  ACTIVATION: bern
  DEGREE: 16
  
DATASET: staliro

CHECKPOINT:
  DIR: experiments/staliro/
  # LOAD: False
  LOAD: True
  PATH_TO_CKPT: "/home/koh/work/experiments/staliro/test/test/checkpoint_best_model.pth"

EXPERIMENT:
  NAME: test
  RUN_NAME: test
  DESCRIPTION: Training of FCNNb DeepBern-Nets on staliro dataset. Clean training (without adversarial examples or certified training)"